[entryPoints]
  [entryPoints.http]
  address = ":80"
    # [entryPoints.http.redirect]
    # entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# [acme]
# email = "letsencrypt@kevinvandenbroek.nl"
# storage = "acme.json"
# entryPoint = "https"
# acmeLogging=true 
# onDemand = false
#   [acme.httpChallenge]
#   entryPoint = "http"

# [[acme.domains]]
#   main = "karaokejam.online"
